### ISSUE TITLE
"Upgrade" to STRING 11.5

### ISSUE THREAD

**Issue by cycle20** [cycle20/EZCancerTarget#61]

**Comment by tuhinmallick** [comment]
Is this issue still available then I would like to give it a try.

**Comment by cycle20** [comment]
Hi,
Thank you. You can check the `js` folder.

**Comment by tuhinmallick** [comment]
@cycle20 I hope I understood the issue right and have made a PR.

**Comment by cycle20** [comment]
@tuhinmallick Thank you for your contribution. You can check the PR with my comment. Almost done. Sorry for the unclear "requirement". I do not want to follow STRING releases automatically in the script. This should be a manual process. That is why I would prefer a version-specific API url.

**Comment by cycle20** [comment]
Thank you for your help. This issue is done. :+1:
